# -*- coding: utf-8 -*-
"""simple calculator 1ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19GoCP1NEc_ZtryulKTQ182qk8RqWO36C
"""

print("hello world")
print("kgrcet")
print("welcome to python program")

roll_number = input("enetr your roll number")
print("hello"+roll_number)

import keyword
print("the list of keyword is:")
print(keyword.kwlist)

x=10
print(type(x))
print(x)

age = input("age")
print("i am "+age+"year old")

x = 5
y ="KGRCT"
print(x)
print(y)

x = 4
x ="hello"
print(x)

x = 500
y ="kgr"
print(str(x)+y)

x = "python"
y = "is"
z = "awesome"
print(x, y, z)

x = "python"
y = "is"
z = "awesome"
print(x+y+z)

x,y=2,3
x



"""#swaping number"""

a =10
b =20
a,b=b,a
print(b)

x , y , z ="orange","banana","cherry"
print(x)
print(y)
print(z)

x = True
print(x)
print(type(x))

a = 5
print(type(a))
b = 5.0
print(type(5.0))
c =2+3j
print(type(c))

s = "welcome to KGRCT"
print(s)
print(type(s))
print(s[1])
print(s[2])
print(s[-1])
print(s[3])

string_one ="i'am studying in kgrct"
string_two = "a new great book"
string_three =string_one +string_two
print(string_three)

print("akhil "*5)

a =[1,2,3]
print(a)
b =["akhil","hi","python",4,5]
print(b)

a = [30, 20,40,70]
a.sort()
a

a =["apple","banana","grapes"]
a.append("mango")
print(a)

a = [10,30, 45,77,99]
print(min(a))

a = ["apple","orange","mango"]
a.insert(2,"green")
print(a)

a = ["apple","orange","mango"]
a.pop()
print(a)

a =10
b =20
a+b

print("multiplication",a/b)

a =10
b =4
a+b

a*b

a/b

a-b

a%b

x = 1024
tip=x*20/100
print(tip)

x =int(input("enter amount:"))
z =(x*20)/100
print(z)

a =20
b =10
print(a<b)
print(a>b)
print(a==b)
print(a>=b)
print(a<=b)



a =True
b =False
print(a and b)
print(a or b)
print(not a)

x =245
y =15
list =[10,20,30,40,50]
if(x not in list):
  print("x is not present in given list")
else:
    print("x is present in given list")


if(y not in list):
  print("y is not present in given list")
else:
    print("y is present in given list")

str1 ="hi"+"hi"
print(str1)

age =30
if(age<21):
  print("you are not eligible for vote")
else:
    print("you can vote")
print("done")

a = 200
b = 33
if(b>a):
  print("b is greater than a")
elif(b>a):
  print("b is equal to a")
else:
  print("a is greater than a")

w = int(input("enter your weight"))
h = int(input("enter your height"))
bmi = w/(h*h)
if(bmi<18.5):
  print("under weight")
  if bmi>=18.5 and x<25:
    print("normal")
  if bmi>=25 and x>30:
    print("over weight")
  if bmi>=30:
    print("obesity")

numbers =[1,2,3,4,5]
for i in numbers:
  print(i)

i = 1
while i<8:
  print(i,end=" ")
  i += 1

i = 1
while i<8:
  print(i)
  i += 1

i = 1
while i<8:
  print(i)
  if i == 4:
    break
    i += i

fo numbers in[1,2,3,5,6,10,11,12]:
if numbers==6:
  break
  print(numbers)
  print('bye')

"""simple calcular"""

from __future__ import division
def add(x,y):
 return x+y
def subtraction(x,y):
 return x-y
def multiplication(x,y):
  return x*y
def divide(x,y):
  if(y!=0):
    return x/y
  else:
    return "denomination has zero"
def calculator():
  print("simple calculator")
  print("chose operation")
  print("1.add")
  print("2.sub")
  print("3.multi")
  print("4.divi")

  while True:
    choice = input("enter choice(1/2/3/4):")
    if choice in ('1','2','3','4'):
      num1 =float(input("enter first number:"))
      num2 =float(input("enter second number:"))
      if choice =='1':
        print(f"the result is:{add(num1,num2)}")
      elif choice =='2':
        print(f"the result is:{subtraction(num1,num2)}")
      elif choice =='3':
        print(f"the result is:{multiplication(num1,num2)}")
      elif choice =='4':
        print(f"the result is:{division(num1,num2)}")
      next_calculation =input("let's do next calculation?(yes/no):")
      if next_calculation.lower()!="yes":
              break
      else:
          print("invalid input")
calculator()

