# -*- coding: utf-8 -*-
"""simple calculator day 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wMYbUNFvwfFG6qKULt4xpVkFKcaEX25c
"""

from __future__ import division
def add(x,y):
 return x+y
def subtraction(x,y):
 return x-y
def multiplication(x,y):
  return x*y
def divide(x,y):
  if(y!=0):
    return x/y
  else:
    return "denomination has zero"
def calculator():
  print("simple calculator")
  print("chose operation")
  print("1.add")
  print("1.sub")
  print("1.multi")
  print("1.divi")

  while true:
    choice = input("enter choice(1/23/4):")
    if choice in ('1','2','3','4'):
      num1 =float(input("enter first number:"))
      num2 =float(input("enter second number:"))
      if choice =='1':
        print(f"the result is:{add(num1,num2)}")
      elif choice =='2':
        print(f"the result is:{subtraction(num1,num2)}")
      elif choice =='3':
        print(f"the result is:{multiplication(num1,num2)}")
      elif choice =='4':
        print(f"the result is:{division(num1,num2)}")
      next_calculation =input("let's do next calculation?(yes/no):")
      if next_calculation.lower()!="yes":
              break
      else:
          print("invalid input")
  calculator()